### ISSUE TITLE
Updates to match ENG version?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps.es-es#1]
The ENG version of MB-910 was updated some time ago by the CO to a new revision that trims down exercises, and thus the ENG version that is now official has only 10 .md files.

Will this localized repo (and all the other MB-910 localized repos) ever get this update?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
updated. 
https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps.es-es/tree/OLPRODLOC/Instructions
